### ISSUE TITLE
Impossible change title on 1.19.4

### ISSUE THREAD

**Issue by Spliterash** [NichtStudioCode/InvUI#25]
I get this error when trying update inventory title.

```log
[DefaultDispatcher-worker-21/WARN]: java.lang.UnsupportedOperationException: Unable to construct this menu by type
[DefaultDispatcher-worker-21/WARN]: 	at net.minecraft.world.inventory.Container.a(Container.java:126)
[DefaultDispatcher-worker-21/WARN]: 	at MtDialog-1.0.0.jar//ru.minetopia.mtdialog.shadow.invui.inventoryaccess.r13.InventoryUtilsImpl.updateOpenInventoryTitle(InventoryUtilsImpl.java:69)
[DefaultDispatcher-worker-21/WARN]: 	at MtDialog-1.0.0.jar//ru.minetopia.mtdialog.shadow.invui.invui.window.AbstractWindow.changeTitle(AbstractWindow.java:306)
```

GUI Init code
```kotlin
val gui = Gui.normal()
    .setStructure(
        ". . . . . . . . .",
        ". . . . . . . . .",
        ". . . . . . . . .",

        ". . . . . . . . .",
        "0 0 0 0 . 1 1 1 1",
        ". . . . . . . . .",
        "2 2 2 2 . 3 3 3 3",
    )
    .apply {
        repeat(4) { i ->
            addIngredient(i.digitToChar(), SimpleItem(item(i)) { click(i) })
        }
    }
    .build()

window = Window
    .merged()
    .setGui(gui)
    .setTitle(AdventureComponentWrapper(createBuilder().build()))
    .build(player)
```
Title change code
```kotlin
window.changeTitle(AdventureComponentWrapper(builder.build()))
```

Server: Pufferfish 1.19.4
InvUI: xyz.xenondevs.invui:invui:1.0-SNAPSHOT

**Comment by Spliterash** [comment]
I dont know why, but problem exist only in first 1-2 minute, after server start
