### ISSUE TITLE
Is there support for 1.19.4

### ISSUE THREAD

**Issue by tank-o** [NichtStudioCode/InvUI#27]
It says 1.19 support but I loaded into my 1.19.4 server and this happens. Any ideas what might cause this or is the package just not updated for 1.19.4?

```
org.bukkit.command.CommandException: Unhandled exception executing command 'ml' in plugin MLcore v1.0-SNAPSHOT
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R3.CraftServer.dispatchCommand(CraftServer.java:906) ~[paper-1.19.4.jar:git-Paper-499]
	at org.bukkit.craftbukkit.v1_19_R3.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[paper-1.19.4.jar:git-Paper-499]
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264) ~[paper-1.19.4.jar:?]
	at net.minecraft.commands.Commands.performCommand(Commands.java:322) ~[?:?]
	at net.minecraft.commands.Commands.performCommand(Commands.java:306) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2289) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$20(ServerGamePacketListenerImpl.java:2249) ~[?:?]
	at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.4.jar:git-Paper-499]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1342) ~[paper-1.19.4.jar:git-Paper-499]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.19.4.jar:git-Paper-499]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1319) ~[paper-1.19.4.jar:git-Paper-499]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1312) ~[paper-1.19.4.jar:git-Paper-499]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1290) ~[paper-1.19.4.jar:git-Paper-499]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1178) ~[paper-1.19.4.jar:git-Paper-499]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[paper-1.19.4.jar:git-Paper-499]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NoClassDefFoundError: org/bukkit/craftbukkit/v1_19_R2/inventory/CraftContainer
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:375) ~[?:?]
	at de.studiocode.inventoryaccess.util.ReflectionUtils.getImplClass(ReflectionUtils.java:31) ~[MLcore-1.0-SNAPSHOT.jar:?]
	at de.studiocode.inventoryaccess.version.InventoryAccess.<clinit>(InventoryAccess.java:18) ~[MLcore-1.0-SNAPSHOT.jar:?]
	at de.studiocode.invui.item.builder.BaseItemBuilder.get(BaseItemBuilder.java:87) ~[MLcore-1.0-SNAPSHOT.jar:?]
	at de.studiocode.invui.item.builder.ItemBuilder.get(ItemBuilder.java:8) ~[MLcore-1.0-SNAPSHOT.jar:?]
	at de.studiocode.invui.item.builder.BaseItemBuilder.getFor(BaseItemBuilder.java:142) ~[MLcore-1.0-SNAPSHOT.jar:?]
	at de.studiocode.invui.item.builder.ItemBuilder.getFor(ItemBuilder.java:8) ~[MLcore-1.0-SNAPSHOT.jar:?]
	at de.studiocode.invui.gui.SlotElement$ItemSlotElement.getItemStack(SlotElement.java:35) ~[MLcore-1.0-SNAPSHOT.jar:?]
	at de.studiocode.invui.window.impl.BaseWindow.redrawItem(BaseWindow.java:69) ~[MLcore-1.0-SNAPSHOT.jar:?]
	at de.studiocode.invui.window.impl.single.SingleWindow.initItems(SingleWindow.java:40) ~[MLcore-1.0-SNAPSHOT.jar:?]
	at de.studiocode.invui.window.impl.single.SingleWindow.<init>(SingleWindow.java:34) ~[MLcore-1.0-SNAPSHOT.jar:?]
	at de.studiocode.invui.window.impl.single.SimpleWindow.<init>(SimpleWindow.java:16) ~[MLcore-1.0-SNAPSHOT.jar:?]
	at de.studiocode.invui.window.impl.single.SimpleWindow.<init>(SimpleWindow.java:33) ~[MLcore-1.0-SNAPSHOT.jar:?]
	at de.studiocode.invui.window.impl.single.SimpleWindow.<init>(SimpleWindow.java:49) ~[MLcore-1.0-SNAPSHOT.jar:?]
	at de.studiocode.invui.window.impl.single.SimpleWindow.<init>(SimpleWindow.java:57) ~[MLcore-1.0-SNAPSHOT.jar:?]
	at de.studiocode.invui.window.impl.single.SimpleWindow.<init>(SimpleWindow.java:61) ~[MLcore-1.0-SNAPSHOT.jar:?]
	at tanko.mlcore.guis.menus.MLMenu.open(MLMenu.java:25) ~[MLcore-1.0-SNAPSHOT.jar:?]
	at tanko.mlcore.commands.ML.mlMain(ML.java:195) ~[MLcore-1.0-SNAPSHOT.jar:?]
	at tanko.mlcore.commands.ML.onCommand(ML.java:51) ~[MLcore-1.0-SNAPSHOT.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	... 23 more
```

**Comment by tank-o** [comment]
Okay I can see that you made changes for 1.19.4, but there is not a maven package beyond 0.10.2 that I can see, which is what I already have

**Comment by NichtStudioCode** [comment]
Support for 1.19.4 is available for the unfinished snapshot version of InvUI-1.0 under `xyz.xenondevs.invui:invui:1.0-SNAPSHOT`. The related documentation can be found [here](https://xenondevs.xyz/docs-dev/invui/)
