### ISSUE TITLE
Issue on opening GUI

### ISSUE THREAD

**Issue by Emibergo02** [NichtStudioCode/InvUI#48]
```
[17:46:41 WARN]: [HuskTowns] Task #12368 for HuskTowns v2.5.4-561c472-indev generated an exception
java.lang.ExceptionInInitializerError: null
        at net.william278.husktowns.libraries.invui.window.NormalMergedWindowImpl$BuilderImpl.build(NormalMergedWindowImpl.java:44) ~[HuskTowns-Plugin-2.5.4-561c472-indev.jar:?]
        at net.william278.husktowns.libraries.invui.window.AbstractWindow$AbstractBuilder.open(AbstractWindow.java:570) ~[HuskTowns-Plugin-2.5.4-561c472-indev.jar:?]
        at dev.unnm3d.kalyaclaims.gui.BukkitGUIManager.lambda$openTownGUI$0(BukkitGUIManager.java:153) ~[HuskTowns-Plugin-2.5.4-561c472-indev.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.20.1.jar:git-Purpur-2044]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480) ~[purpur-1.20.1.jar:git-Purpur-2044]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1507) ~[purpur-1.20.1.jar:git-Purpur-2044]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:487) ~[purpur-1.20.1.jar:git-Purpur-2044]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1421) ~[purpur-1.20.1.jar:git-Purpur-2044]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1192) ~[purpur-1.20.1.jar:git-Purpur-2044]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.1.jar:git-Purpur-2044]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "java.lang.Class.isInstance(Object)" because "net.william278.husktowns.libraries.inventoryaccess.util.ReflectionRegistry.PAPER_PLUGIN_CLASS_LOADER_CLASS" is null
        at net.william278.husktowns.libraries.invui.InvUI.tryFindPlugin(InvUI.java:50) ~[HuskTowns-Plugin-2.5.4-561c472-indev.jar:?]
        at net.william278.husktowns.libraries.invui.InvUI.getPlugin(InvUI.java:36) ~[HuskTowns-Plugin-2.5.4-561c472-indev.jar:?]
        at net.william278.husktowns.libraries.invui.window.AbstractWindow.<clinit>(AbstractWindow.java:42) ~[HuskTowns-Plugin-2.5.4-561c472-indev.jar:?]
        ... 11 more
```
it is shaded
running on Purpur 1.20.1  (might be this)

my gradle

    implementation "xyz.xenondevs.invui:invui-core:1.15"
    implementation "xyz.xenondevs.invui:inventory-access-r14:1.15"
    ...
    relocate 'xyz.xenondevs', 'net.william278.husktowns.libraries'

**Comment by NichtStudioCode** [comment]
Resolved in [discord conversation](https://discord.com/channels/859080327096172544/1005893933458538537/1153692132025057310), plugin instance needed to be set manually via `InvUI.getInstance().setPlugin`.
